name: Docker Build CI

# Tetikleyici: 'main' dalına her push yapıldığında bu iş başlasın
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest # GitHub'ın Linux sunucusunda çalış

    steps:
      # 1. Kodunu sunucuya çek
      - name: Kodları Çek (Checkout)
        uses: actions/checkout@v3

      # 2. Docker Build aracını kur
      - name: Docker Buildx Kurulumu
        uses: docker/setup-buildx-action@v2

      # 3. İmajı Build Et (Test)
      # push: false diyoruz çünkü şimdilik sadece "build oluyor mu" diye bakıyoruz.
      - name: Build Test
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: simple-docker-nginx:latest
